import type { MetadataRoute } from 'next';
import { getCategories } from '../src/lib/data/categories';
import { getProvinces } from '../src/lib/data/provinces';
import { getApprovedContractorSlugsForSitemap } from '../src/lib/data/contractors';
import { getSiteUrl } from '../src/lib/env';

/**
 * Phase 11 (Issue #9) — "Generate a valid dynamic sitemap containing
 * indexable public routes." Every URL here matches one of the pages this
 * phase marked indexable (see each page's own generateMetadata/metadata
 * export) — nothing appears here that isn't also indexable through its
 * own page metadata, and nothing private/admin/auth/non-approved does:
 * - `/`, `/search`, `/contractors/register` — static public pages.
 * - one `/contractors/[slug]` per REAL, currently-approved contractor
 *   (getApprovedContractorSlugsForSitemap() is RLS-scoped to
 *   `status = 'approved'`, same as the profile page itself — a pending/
 *   rejected/suspended contractor's slug can never appear here).
 * - one `/search?category=<slug>` per real category and one
 *   `/search?province=<slug>` per real province — Issue #9's "province/
 *   category landing/filter pages can have unique indexable URLs"; a
 *   bounded, real list (order of tens/hundreds), not the "hundreds of
 *   thin doorway pages" the issue says to avoid — every one of these
 *   matches exactly what /search's own generateMetadata (Section
 *   getSearchIndexability()) already treats as indexable.
 * No `/search?q=...`, no combined-filter, no page>1 URLs — those are
 * marked noindex on the page itself and correctly never listed here.
 *
 * `sitemap.ts` is cached/statically generated by default (would bake in
 * whichever contractors were approved AT BUILD TIME, permanently, until
 * the next deploy — the same staleness problem the registration page's
 * own `force-dynamic` comment already describes for provinces/
 * categories). A newly-approved contractor must appear here without
 * waiting for a redeploy, so this always fetches fresh, same as
 * app/contractors/register/page.tsx and the admin pages.
 */
export const dynamic = 'force-dynamic';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const siteUrl = getSiteUrl();
  const [categories, provinces, contractors] = await Promise.all([
    getCategories(),
    getProvinces(),
    getApprovedContractorSlugsForSitemap(),
  ]);

  const entries: MetadataRoute.Sitemap = [
    { url: `${siteUrl}/`, changeFrequency: 'weekly', priority: 1 },
    { url: `${siteUrl}/search`, changeFrequency: 'daily', priority: 0.8 },
    { url: `${siteUrl}/contractors/register`, changeFrequency: 'monthly', priority: 0.5 },
  ];

  for (const contractor of contractors) {
    entries.push({
      url: `${siteUrl}/contractors/${contractor.slug}`,
      lastModified: contractor.updated_at,
      changeFrequency: 'weekly',
      priority: 0.6,
    });
  }

  for (const category of categories) {
    entries.push({
      url: `${siteUrl}/search?category=${encodeURIComponent(category.slug)}`,
      changeFrequency: 'weekly',
      priority: 0.5,
    });
  }

  for (const province of provinces) {
    entries.push({
      url: `${siteUrl}/search?province=${encodeURIComponent(province.slug)}`,
      changeFrequency: 'weekly',
      priority: 0.4,
    });
  }

  return entries;
}
